// ===========================================
// BANCO DE 25 CUENTOS PARA EL JUEGO DE LECTURA
// Cada cuento: título, texto (300+ palabras),
// 3 preguntas con su respuesta correcta marcada,
// y un prompt de escritura creativa.
// ===========================================

const STORIES = [
  {
    id: 1,
    title: "El Gato Curioso",
    text: "Luna era una gata muy curiosa de pelaje suave color gris plateado que vivía en una casa acogedora con un jardín enorme lleno de sorpresas. Cada mañana, después del desayuno, Luna salía por la pequeña puerta especial para gatos y comenzaba su rutina de exploración, revisando cada rincón como si fuera la primera vez que lo viera. Le encantaba olfatear las flores, trepar a la cerca de madera y observar a los pájaros que volaban sobre el tejado. Un soleado día de primavera, mientras paseaba entre los rosales, Luna vio algo que nunca había visto antes: una mariposa amarilla brillante que volaba de flor en flor, visitando las rosas rojas, los tulipanes anaranjados y las margaritas blancas. La mariposa parecía bailar en el aire, moviéndose con una gracia que fascinó a Luna por completo. Decidida a jugar con ella, la gata comenzó a perseguirla saltando entre los arbustos y agachándose entre las plantas como una pequeña cazadora. Pero la mariposa era extremadamente rápida y elegante, y cada vez que Luna creía que finalmente la alcanzaría, la mariposa daba un giro inesperado y se escapaba volando hacia otra flor. Después de mucho correr, saltar y maullar de emoción, Luna finalmente se cansó. Sus patitas estaban agotadas y su respiración era agitada. Decidió entonces ir a descansar bajo un gran árbol que ofrecía una sombra fresca y agradable. Se acomodó entre las raíces, cerró los ojos lentamente y, sin darse cuenta, se quedó profundamente dormida, soñando quizás con mariposas y jardines infinitos. Pasado un buen rato, Luna despertó al sentir algo muy suave haciéndole cosquillas en la nariz. Cuando abrió los ojos sorprendida, descubrió que la misma mariposa amarilla se había posado justo ahí, tranquila y confiada, como si quisiera hacerse amiga suya. Luna no se movió, solo sonrió a su manera felina, disfrutando de ese momento mágico. Aprendió, sin saberlo del todo, que a veces las cosas más hermosas de la vida llegan solas cuando dejamos de perseguirlas con tanta prisa.",
    questions: [
      { q: "¿Cómo se llamaba la gata?", options: ["Luna", "Estrella", "Miau"], correctText: "Luna" },
      { q: "¿De qué color era la mariposa?", options: ["Azul", "Amarilla", "Roja"], correctText: "Amarilla" },
      { q: "¿Qué hizo Luna cuando se cansó?", options: ["Volvió a casa", "Se durmió bajo un árbol", "Siguió corriendo"], correctText: "Se durmió bajo un árbol" }
    ],
    writingPrompt: "¿Qué crees que pasó después entre Luna y la mariposa? Escribe tu propia continuación de la historia."
  },
  {
    id: 2,
    title: "La Aventura del Ratón",
    text: "Pipo era un ratón pequeño y muy inteligente que vivía escondido en una gran biblioteca llena de libros antiguos y polvorientos. Durante el día se quedaba quietecito en su pequeña madriguera detrás de un estante, escuchando los pasos de los visitantes y el suave murmullo de las páginas pasando. Pero por las noches, cuando todo quedaba en silencio y la bibliotecaria apagaba las luces, Pipo salía con cuidado a explorar su reino secreto. Le encantaba trepar por las estanterías más altas usando pequeñas cuerdas hechas de hilo que había encontrado, y leer, a su manera, los títulos dorados de los libros más antiguos. Una noche especial de invierno, mientras explorada un rincón que nunca había visitado, Pipo encontró un libro enorme y pesado sobre dragones, mucho más grande que cualquier otro libro de la biblioteca. La portada de cuero tenía dibujado un dragón dorado que parecía brillar suavemente bajo la luz de la luna que entraba por la ventana. Con mucho esfuerzo, empujando con todas sus fuerzas, Pipo logró abrir apenas una página del libro. De repente, entre un destello de luz mágica y dorada, apareció frente a él un dragón diminuto, no más grande que su propia pata. El pequeño dragón tenía escamas de color verde esmeralda que brillaban como joyas y unas alas transparentes parecidas a las de una libélula. Con una voz suave y amigable, el dragón habló: 'Hola, soy Rex. He estado esperando durante siglos a que alguien con corazón curioso abriera este libro. ¿Quieres ser mi amigo?' Pipo, aunque sorprendido al principio, sintió una alegría enorme y aceptó de inmediato. Desde ese mágico día, Pipo y Rex se volvieron compañeros inseparables. Cada noche se reunían entre las estanterías para leer juntos los libros de la biblioteca, viviendo en su imaginación increíbles aventuras: viajaban a través de mapas antiguos, exploraban castillos dibujados en las ilustraciones y resolvían misterios escondidos entre las páginas. Pipo descubrió que la lectura, compartida con un buen amigo, podía convertir cualquier noche solitaria en una aventura inolvidable.",
    questions: [
      { q: "¿Dónde vivía Pipo?", options: ["En un queso", "En una biblioteca", "En un jardín"], correctText: "En una biblioteca" },
      { q: "¿De qué color era el dragón Rex?", options: ["Dorado", "Verde esmeralda", "Rojo fuego"], correctText: "Verde esmeralda" },
      { q: "¿Cuándo salía Pipo a explorar?", options: ["Por las mañanas", "Por las tardes", "Por las noches"], correctText: "Por las noches" }
    ],
    writingPrompt: "Imagina que encuentras un libro mágico. ¿Qué personaje saldría de él y qué aventura vivirían juntos?"
  },
  {
    id: 3,
    title: "El Árbol Mágico",
    text: "En medio de un bosque encantado había un árbol muy especial y antiguo, mucho más grande que cualquier otro árbol del bosque. Su tronco era grueso y estaba lleno de nudos que, si se miraban con atención, parecían formar rostros sabios y amables. Lo más asombroso de este árbol era que sus hojas cambiaban de color según el estado de ánimo de la persona o animal que se acercaba a él. Los animales del bosque lo conocían muy bien desde hacía generaciones, y a menudo iban a visitarlo cuando se sentían tristes o necesitaban un poco de consuelo, sabiendo que el árbol siempre encontraba una manera de ayudarlos. Un día, una niña llamada Ana llegó caminando despacio hasta el bosque, sintiéndose muy triste porque había tenido un día muy difícil en la escuela: se había peleado con su mejor amiga y había sacado una mala nota en un examen. Cuando se acercó al árbol mágico y se sentó junto a sus raíces, ocurrió algo sorprendente: todas las hojas del árbol comenzaron a cambiar lentamente, volviéndose de un azul profundo como las aguas del mar en un día nublado. Ana se quedó mirando, sorprendida, sin entender bien qué estaba sucediendo. Se sentó junto al tronco y, sin poder contenerse más, comenzó a llorar suavemente. En ese preciso momento, varios pájaros de colores brillantes bajaron volando desde las ramas más altas y comenzaron a cantar las melodías más alegres y dulces que Ana había escuchado en toda su vida. Poco a poco, mientras escuchaba el canto, la niña empezó primero a sonreír, y después, sin poder evitarlo, a reír con las divertidas travesuras de los pájaros que saltaban y bailaban frente a ella. A medida que la tristeza de Ana iba desapareciendo, las hojas del árbol fueron cambiando lentamente: del azul profundo pasaron al verde fresco, luego al amarillo brillante, y finalmente se volvieron doradas, como pequeños rayos de sol atrapados entre las ramas. Entonces, el árbol le habló con una voz suave como el viento entre las hojas: 'Ana, recuerda siempre que la alegría es el mejor regalo que puedes dar, tanto a ti misma como a los demás.' Ana sonrió, secándose las últimas lágrimas, y comprendió que sonreír y buscar la belleza en las pequeñas cosas puede hacer que todo en la vida parezca más bonito y especial.",
    questions: [
      { q: "¿Qué tenía de especial el árbol?", options: ["Daba frutos mágicos", "Sus hojas cambiaban de color", "Era muy alto"], correctText: "Sus hojas cambiaban de color" },
      { q: "¿De qué color se pusieron las hojas cuando Ana estaba triste?", options: ["Rojas", "Azul profundo", "Verdes"], correctText: "Azul profundo" },
      { q: "¿Quiénes ayudaron a Ana a sentirse mejor?", options: ["Los pájaros cantores", "Otros niños", "Un mago"], correctText: "Los pájaros cantores" }
    ],
    writingPrompt: "Si tuvieras un árbol mágico en tu jardín, ¿qué poder especial tendría y cómo te ayudaría?"
  },
  {
    id: 4,
    title: "El Robot Jardinero",
    text: "En una ciudad del futuro llena de edificios altos y calles ordenadas vivía un robot llamado Verde, que tenía una misión muy especial y diferente a la de los demás robots: cuidar de todas las plantas de la ciudad. Verde no era como los otros robots que trabajaban en las grandes fábricas o que limpiaban las calles automáticamente durante la noche. Él tenía algo distinto, un corazón mecánico que, según decía, latía con verdadero amor por la naturaleza. Cada mañana, justo cuando salía el sol y sus rayos comenzaban a calentar la ciudad, Verde se despertaba de su modo de descanso y recorría pacientemente todos los parques, jardines y plazas. Regaba las flores con mucho cuidado, calculando la cantidad exacta de agua que cada una necesitaba, podaba los árboles con movimientos delicados de sus brazos mecánicos, y hablaba suavemente con cada planta mientras trabajaba, como si fueran viejas amigas. Aunque era un robot hecho de metal y cables, Verde había aprendido, observando durante años, que las plantas parecían crecer mejor y más fuertes cuando alguien les hablaba con cariño y paciencia. Un día, mientras hacía su recorrido habitual, Verde descubrió un rincón olvidado de la ciudad donde no crecía absolutamente nada. La tierra estaba seca, agrietada y de un color gris apagado, como si hubiera sido abandonada hacía mucho tiempo. Verde decidió, sin dudarlo, que ese sería su nuevo gran proyecto. Durante muchas semanas trabajó sin descanso: trajo carretillas llenas de tierra fresca y nutritiva, plantó cuidadosamente pequeñas semillas de distintas flores y árboles, y regó cada rincón con una paciencia admirable, día tras día, sin importar el clima. Poco a poco, como por arte de magia, comenzaron a brotar pequeños tallos verdes que crecían un poquito más cada semana. Los niños del barrio, curiosos, empezaron a venir cada tarde después de la escuela para observar cómo crecía lentamente el jardín de Verde, haciendo preguntas y ayudando a quitar las malas hierbas. Cuando finalmente, después de meses de trabajo dedicado, el jardín estuvo completamente lleno de flores de todos los colores y pequeños árboles llenos de hojas, toda la ciudad organizó una gran celebración. Verde, parado entre las flores que él mismo había cuidado, sintió una felicidad enorme. Había logrado enseñar a toda la ciudad que con esfuerzo constante, mucha paciencia y verdadero amor, se pueden crear cosas realmente maravillosas, incluso en los lugares que parecían los más abandonados e imposibles.",
    questions: [
      { q: "¿Cómo se llamaba el robot?", options: ["Azul", "Verde", "Rojo"], correctText: "Verde" },
      { q: "¿Cuál era la misión especial de Verde?", options: ["Limpiar calles", "Cuidar plantas", "Construir casas"], correctText: "Cuidar plantas" },
      { q: "¿Qué creó Verde en el rincón abandonado?", options: ["Un edificio", "Un jardín", "Una tienda"], correctText: "Un jardín" }
    ],
    writingPrompt: "Si tuvieras un robot amigo, ¿qué le enseñarías a hacer y qué aventuras vivirían juntos?"
  },
  {
    id: 5,
    title: "La Tortuga Viajera",
    text: "Lola era una tortuga marina que, desde muy pequeña, soñaba con algo que parecía imposible para las demás tortugas de su familia: conocer todos los océanos del mundo. A diferencia de sus hermanas y primas, que preferían quedarse tranquilas en las cálidas aguas tropicales donde habían nacido, Lola sentía una curiosidad enorme y una emoción especial cada vez que pensaba en lugares lejanos y desconocidos. Un día, después de despedirse con cariño de su mamá y de todos sus hermanos, reuniendo todo el valor que tenía, Lola comenzó finalmente su gran aventura, nadando hacia el horizonte sin saber exactamente lo que encontraría. Nadó durante muchos días y muchas noches seguidas, conociendo en su camino a delfines juguetones que saltaban a su alrededor, a pulpos tímidos que se escondían entre las rocas apenas la veían pasar, y a peces de mil colores diferentes que nadaban en grandes grupos brillantes. En cada nuevo lugar que visitaba, Lola aprendía siempre algo distinto y valioso. Los delfines, divertidos, le enseñaron a saltar elegantemente sobre las olas más grandes; los pulpos, con mucha paciencia, le mostraron técnicas secretas para esconderse entre las rocas cuando sentía algún peligro cercano; y los peces más viejos le contaron historias antiguas y misteriosas sobre el fondo del océano, transmitidas de generación en generación. Durante su largo viaje, Lola también tuvo la suerte de descubrir arrecifes de coral maravillosos que brillaban bajo el agua como auténticas joyas de colores, y nadó muy cerca de enormes ballenas que cantaban canciones profundas y misteriosas que parecían venir desde el principio de los tiempos. Después de muchos meses explorando sin parar, recorriendo distancias que jamás había imaginado, Lola finalmente sintió en su corazón que era momento de regresar a casa. Cuando llegó de vuelta, todas las tortugas de su familia, emocionadas, se reunieron a su alrededor para escuchar con atención sus increíbles historias de viajes. Fue entonces cuando Lola se dio cuenta de algo muy importante: aunque viajar y explorar lugares nuevos era realmente emocionante y le había enseñado tanto, compartir después esas experiencias con quienes amaba era, sin duda, aún más especial y reconfortante. Desde aquel día, Lola decidió hacer un gran viaje cada año, explorando siempre lugares distintos, pero siempre regresando a casa con nuevas y maravillosas historias para contar a su familia.",
    questions: [
      { q: "¿Qué tipo de animal era Lola?", options: ["Un pez", "Una tortuga marina", "Un delfín"], correctText: "Una tortuga marina" },
      { q: "¿Qué le enseñaron los delfines a Lola?", options: ["A esconderse", "A saltar sobre las olas", "A cantar"], correctText: "A saltar sobre las olas" },
      { q: "¿Qué hizo Lola al regresar a casa?", options: ["Se durmió", "Compartió sus historias", "Volvió a irse"], correctText: "Compartió sus historias" }
    ],
    writingPrompt: "Si pudieras viajar a cualquier lugar como Lola, ¿dónde irías y qué te gustaría descubrir?"
  },
  {
    id: 6,
    title: "El Pintor de Arcoíris",
    text: "Don Tomás era un señor mayor de cabello blanco y manos arrugadas que vivía solo en una pequeña casa de piedra al final de un pueblo rodeado de colinas verdes. Todos los días, sin falta, después de tomar su desayuno tranquilo junto a la ventana, Don Tomás subía caminando despacio hasta una colina cercana, cargando con cuidado su caballete de madera, sus pinceles favoritos y una caja vieja llena de pinturas de todos los colores. Lo que ningún vecino del pueblo sabía era que Don Tomás guardaba un secreto verdaderamente mágico: cuando pintaba con todo su corazón un arcoíris en uno de sus cuadros, ese mismo arcoíris aparecía de verdad, brillante y enorme, en el cielo real sobre el pueblo. Un día particularmente difícil, el pueblo entero se encontraba muy triste y preocupado porque llevaban ya muchas semanas sin que cayera ni una sola gota de lluvia, y los campos de cultivo estaban completamente secos y agrietados. Los agricultores caminaban con el rostro preocupado revisando sus cosechas, y los niños, normalmente alegres, ya casi no salían a jugar por las calles polvorientas. Don Tomás, observando con tristeza la situación desde su ventana, decidió que había llegado el momento de usar su magia especial para ayudar a todos. Subió decidido hasta su colina favorita y comenzó a pintar, con más dedicación que nunca, el arcoíris más grande y hermoso que había creado en toda su vida. Eligió con cuidado los colores más brillantes de su caja: rojo intenso como las amapolas del campo, naranja cálido como el atardecer, amarillo brillante como los rayos del sol, verde fresco como la hierba después de la lluvia, azul profundo como el mar más lejano, añil oscuro como el cielo nocturno, y violeta suave como las flores de lavanda que crecían cerca de su casa. Mientras pintaba con todo su corazón y su concentración puesta en cada trazo, las nubes grises comenzaron poco a poco a juntarse silenciosamente en el cielo sobre el pueblo. De repente, sin previo aviso, empezó a caer una lluvia suave y constante. Y justo cuando los primeros rayos de sol lograron atravesar tímidamente las nubes, apareció en el cielo, exactamente igual, el arcoíris que Don Tomás acababa de terminar de pintar en su lienzo. Todo el pueblo, emocionado, salió corriendo a las calles para contemplar juntos el hermoso arcoíris y celebrar con alegría la lluvia tan necesitada. Ese día, Don Tomás, observando todo desde su colina con una sonrisa tranquila, supo en su corazón que su arte había logrado traer esperanza y felicidad verdadera a todas las personas que tanto quería.",
    questions: [
      { q: "¿Cuál era el poder secreto de Don Tomás?", options: ["Hacer llover", "Sus arcoíris pintados se hacían reales", "Volar"], correctText: "Sus arcoíris pintados se hacían reales" },
      { q: "¿Por qué estaba triste el pueblo?", options: ["Hacía mucho frío", "No llovía", "No había comida"], correctText: "No llovía" },
      { q: "¿Cuántos colores tiene un arcoíris según el cuento?", options: ["Cinco colores", "Seis colores", "Siete colores"], correctText: "Siete colores" }
    ],
    writingPrompt: "Si pudieras tener un poder mágico como Don Tomás, ¿qué poder elegirías y cómo lo usarías para ayudar a otros?"
  },
  {
    id: 7,
    title: "La Hormiga Inventora",
    text: "En un hormiguero muy grande y perfectamente organizado, escondido bajo las raíces de un viejo roble, vivía una hormiga pequeña llamada Chispa. Mientras todas las demás hormigas del hormiguero seguían cuidadosamente las mismas rutinas día tras día, llevando granos de comida de un lado a otro y construyendo nuevos túneles siguiendo siempre el mismo método de siempre, Chispa era diferente: pasaba su tiempo libre pensando en nuevas ideas y formas distintas de hacer las tareas cotidianas. A las demás hormigas trabajadoras les parecía una hormiga un poco extraña, incluso algo despistada, pero la reina hormiga, mucho más sabia y observadora, siempre había notado algo especial y valioso en ella. Un día, durante la temporada de lluvias, el hormiguero enfrentó un problema verdaderamente grave: las fuertes lluvias habían comenzado a inundar varios de los túneles más importantes, y el agua seguía entrando sin parar por todas partes. Todas las hormigas corrían de un lado a otro, completamente asustadas y sin saber qué hacer para detener la inundación que amenazaba con destruir su hogar. Fue entonces cuando Chispa, en medio de todo el caos, tuvo una idea verdaderamente brillante. Usando pequeñas hojas que encontró cerca de la entrada, ramitas delgadas y algunas gotas de resina pegajosa que sacó de la corteza de los árboles cercanos, comenzó a construir cuidadosamente un sistema completo de pequeños canales que pudiera desviar el agua lejos del hormiguero. Trabajó sin descanso durante muchas horas, probando diferentes diseños uno tras otro, corrigiendo errores y ajustando cada detalle hasta encontrar finalmente el diseño perfecto que funcionara de verdad. Cuando el sistema de canales quedó completamente terminado, el agua que antes inundaba los túneles comenzó a salir ordenadamente por los caminos que Chispa había diseñado con tanto esfuerzo. Gracias a su creatividad, su paciencia y su ingenio, el hormiguero entero logró salvarse de la inundación. A partir de ese momento tan importante, todas las hormigas, incluso las más tradicionales, comenzaron a valorar y respetar profundamente las ideas diferentes que siempre había tenido Chispa. La reina, agradecida y admirada, decidió nombrarla oficialmente Jefa de Inventos del hormiguero, y le entregó un pequeño laboratorio especial donde podía experimentar libremente y crear nuevos dispositivos que ayudaran a mejorar la vida de toda la comunidad. Chispa aprendió, gracias a esta experiencia, que ser diferente de los demás no era algo malo, sino que sus ideas únicas podían realmente ayudar a toda su comunidad cuando más lo necesitaban, y que trabajar juntos valorando las distintas habilidades de cada uno permite superar prácticamente cualquier desafío que se presente.",
    questions: [
      { q: "¿Cómo se llamaba la hormiga inventora?", options: ["Rayo", "Chispa", "Trueno"], correctText: "Chispa" },
      { q: "¿Qué problema tenía el hormiguero?", options: ["Falta de comida", "Inundación de túneles", "Mucho calor"], correctText: "Inundación de túneles" },
      { q: "¿Qué usó Chispa para resolver el problema?", options: ["Piedras grandes", "Hojas y ramitas", "Arena"], correctText: "Hojas y ramitas" }
    ],
    writingPrompt: "Imagina que tienes que resolver un problema en tu escuela o casa. ¿Qué invento crearías?"
  },
  {
    id: 8,
    title: "El Faro de las Estrellas",
    text: "En la punta de un acantilado alto y rocoso que miraba directamente hacia el mar abierto se encontraba un antiguo faro de piedra que, desde hacía ya varios años, había dejado de funcionar por completo. Don Miguel, quien había sido el farero encargado durante más de cuarenta años, se había jubilado tiempo atrás porque los barcos modernos, equipados con sistemas de GPS y computadoras avanzadas, ya no necesitaban la luz del faro para guiarse de noche entre las rocas peligrosas. El viejo faro, antes lleno de vida y actividad, ahora permanecía abandonado, silencioso y, según contaban algunos vecinos, también un poco triste. Una noche tranquila de verano, una niña curiosa llamada Sofía se encontraba acampando junto a su familia muy cerca del acantilado. Como no podía conciliar el sueño, decidió salir despacio de su tienda de campaña para observar las estrellas que brillaban intensamente en el cielo despejado. Caminando sin rumbo fijo, llegó hasta el faro abandonado y, para su sorpresa, encontró la puerta principal entreabierta. Llena de curiosidad, entró con cuidado y comenzó a subir las antiguas escaleras de caracol hasta llegar finalmente a la cima del faro. Allí, para su sorpresa, encontró a Don Miguel, quien había regresado esa noche, como hacía de vez en cuando, para visitar el lugar que tanto había significado en su vida. El anciano, con una sonrisa amable, le explicó pacientemente a Sofía cómo funcionaba el enorme mecanismo del faro y le contó historias fascinantes sobre todos los barcos que había ayudado a guiar durante décadas enteras de tormentas furiosas y noches completamente oscuras. Le habló también de marineros valientes que habían cruzado mares peligrosos, de ballenas gigantes que solían pasar cerca de la costa cantando melodías profundas, y de auroras boreales que en ocasiones especiales pintaban el cielo nocturno con colores increíbles. Sofía escuchaba cada palabra completamente fascinada, sin perder ni un solo detalle de aquellas historias. Entonces, de repente, se le ocurrió una idea verdaderamente maravillosa: '¿Y si convertimos este faro abandonado en un observatorio de estrellas para que todos puedan disfrutarlo?', propuso emocionada. Don Miguel sonrió ampliamente ante la idea, y juntos comenzaron a planear cómo hacerlo realidad. Con la ayuda entusiasta de todo el pueblo, limpiaron cuidadosamente el faro de arriba a abajo, instalaron un telescopio moderno en la parte más alta, y finalmente lo abrieron al público para que cualquier persona pudiera visitarlo. Desde entonces, en lugar de guiar barcos perdidos en el mar, el viejo faro comenzó a guiar a las personas en la exploración del inmenso universo, ayudándolas a soñar con las estrellas. Don Miguel, feliz y con un nuevo propósito, volvió a sentirse útil enseñando a niños y adultos sobre las constelaciones, los planetas lejanos y todas las maravillas escondidas en el espacio.",
    questions: [
      { q: "¿Por qué el faro estaba abandonado?", options: ["Estaba roto", "Los barcos ya no lo necesitaban", "Don Miguel estaba enfermo"], correctText: "Los barcos ya no lo necesitaban" },
      { q: "¿Qué encontró Sofía en la cima del faro?", options: ["Un tesoro", "A Don Miguel", "Un pájaro"], correctText: "A Don Miguel" },
      { q: "¿En qué convirtieron el faro?", options: ["En un museo", "En un observatorio de estrellas", "En un restaurante"], correctText: "En un observatorio de estrellas" }
    ],
    writingPrompt: "Si pudieras convertir un lugar abandonado en algo nuevo y útil, ¿qué sería y para qué lo usarías?"
  },
  {
    id: 9,
    title: "El Perro Cartero",
    text: "Toby era un alegre perro golden retriever de pelaje dorado y brillante que vivía felizmente junto a su familia en un pequeño pueblo rodeado de montañas. Desde siempre, Toby disfrutaba mucho acompañando cada mañana al cartero del pueblo en su recorrido habitual, conociendo así, calle por calle, absolutamente todas las rutas y todas las casas donde vivían los vecinos. Un día, sin embargo, el cartero oficial se enfermó gravemente y, durante varias semanas, no pudo continuar repartiendo el correo como de costumbre. La familia de Toby, observando lo bien que el perro conocía cada rincón del pueblo, tuvo entonces una idea poco común pero interesante: ¿y si Toby se encargaba temporalmente de repartir el correo mientras el cartero se recuperaba en su casa? Decididos a intentarlo, le colocaron un pequeño chaleco especial con varios bolsillos a los costados, y así comenzó la nueva aventura de Toby como cartero del pueblo. Al principio, algunos vecinos se sorprendieron bastante al ver a un perro entregando cuidadosamente las cartas en sus puertas, pero con el paso de los días, todos comenzaron a adorar profundamente esta original idea. Toby no solamente entregaba el correo con una eficiencia sorprendente, sino que además llevaba consigo, sin proponérselo, mucha alegría a cada casa que visitaba durante su recorrido diario. Movía la cola con entusiasmo genuino al llegar, se detenía un momento para jugar alegremente con los niños que salían a recibirlo, y parecía saber exactamente cuándo consolar con su compañía silenciosa a aquellas personas que se sentían solas. La señora María, una anciana que vivía completamente sola en lo alto de la colina, esperaba todos los días con verdadera emoción la visita puntual de Toby. El pequeño Carlos, que en ese momento estaba enfermo y debía permanecer en cama, sentía una gran alegría cada vez que Toby subía pacientemente hasta su habitación llevándole el correo familiar. Cuando finalmente el cartero oficial se recuperó por completo y pudo regresar a su trabajo habitual, el pueblo entero decidió organizar una pequeña reunión para discutir lo sucedido. Todos los vecinos estuvieron completamente de acuerdo en algo importante: Toby se había convertido en un cartero tan especial y querido que merecía seguir desempeñando ese trabajo de alguna manera. Desde aquel día tan especial, Toby y el cartero oficial comenzaron a trabajar juntos en equipo, repartiendo entre los dos no solamente cartas y paquetes, sino también sonrisas sinceras por absolutamente todo el pueblo.",
    questions: [
      { q: "¿Qué raza era Toby?", options: ["Labrador", "Golden retriever", "Pastor alemán"], correctText: "Golden retriever" },
      { q: "¿Por qué Toby comenzó a repartir correo?", options: ["Era su trabajo", "El cartero se enfermó", "Era un juego"], correctText: "El cartero se enfermó" },
      { q: "¿Qué llevaba Toby además del correo?", options: ["Comida", "Alegría y sonrisas", "Juguetes"], correctText: "Alegría y sonrisas" }
    ],
    writingPrompt: "Si tu mascota pudiera tener un trabajo especial, ¿cuál sería y por qué?"
  }
];
